// This file has to be in JavaScript, otherwise @docusaurus/plugin-content-docs doesn't work properly
export default {
    cloud: [
        {
            type: 'autogenerated',
            dirName: '.',
        }
    ],
};